# Default values for template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
application:
  name: overrideHere
  #name: qta-gwce-gasp-helloworld

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

env:

# virtualservice:
#   enabled: true
#   list:
#     - host: "qta-helloworld.onestore.net"
#       gateways: "gateway-public"
#       name: ""

tolerations:
- effect: NoSchedule
  key: kubernetes.azure.com/scalesetpriority
  operator: Equal
  value: spot

strategy:
  enabled: true
  canary:
    maxSurge: "25%"
    maxUnavailable: 0
    steps:
      firstStep:
        setWeight: 25
        pause: 
          duration: 30s 
        analysis:
          templateName: success-health
      secondStep:
        enabled: true
        setWeight: 50
        pause: 
          duration: 30s 
        analysis:
          enabled: false
          templateName: success-health
      thirdStep:
        enabled: true
        setWeight: 75
        pause: 
          duration: 30s 
        analysis:
          enabled: false
          templateName: success-health

analysisPath: /givemejson

podAntiAffinity:
  enabled: true
  labelSelector:
    matchExpressions:
      key: app.kubernetes.io/name

topologySpreadConstraints:
  enabled: true
  maxSkew: 1

livenessProbe:
  enabled: true
  data:
    httpGet:
      path: /health/status.html
      port: 8080
    initialDelaySeconds: 60
readinessProbe: 
  enabled: true
  data:
    httpGet:
      path: /health/status.html
      port: 8080
    initialDelaySeconds: 60
    periodSeconds: 10
startupProbe:
  enabled: true
  data:
    httpGet:
      path: /health/status.html
      port: 8080
    failureThreshold: 10
    periodSeconds: 10

imagePullSecrets: 
  - name: regcred
  
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  # targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}


