apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ .Values.application.name }}
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
    app.kubernetes.io/version: {{ .Values.image.tag }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-template.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "helm-template.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ .Values.application.name }}
        app.kubernetes.io/version: {{ .Values.image.tag }}
    spec:
      affinity:
        {{- if .Values.podAntiAffinity.enabled }}
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions: 
                  - key: {{ .Values.podAntiAffinity.labelSelector.matchExpressions.key | quote }}
                    operator: In
                    values:
                      - {{ .Values.application.name }}
              topologyKey: kubernetes.io/hostname
        {{- end }}
      topologySpreadConstraints:
        {{- if .Values.topologySpreadConstraints.enabled }}
        - maxSkew: {{ .Values.topologySpreadConstraints.maxSkew }}
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels: 
              app.kubernetes.io/instance: {{ .Values.application.name }}
        {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.application.name }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.application.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $value := .Values.env }}
          - name: {{ $key }}
            value: "{{$value}}"
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe.data | nindent 12 }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe.data | nindent 12 }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            {{- toYaml .Values.startupProbe.data | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if .Values.strategy.enabled }}
  strategy:
    canary:
      maxSurge: {{ .Values.strategy.canary.maxSurge }}
      maxUnavailable: {{  .Values.strategy.canary.maxUnavailable }}
      steps:
      - setWeight: {{ .Values.strategy.canary.steps.firstStep.setWeight }}
      - pause: 
          duration: {{ .Values.strategy.canary.steps.firstStep.pause.duration }}
      - analysis:
          templates:
          - templateName: {{ .Values.strategy.canary.steps.firstStep.analysis.templateName }}
          args:
          - name: service-name
            value: {{ .Values.application.name | quote }}
          - name: service-port
            value: {{ .Values.service.port | quote }}
          - name: context-path
            value: {{ .Values.analysisPath | quote }}
      {{- if .Values.strategy.canary.steps.secondStep.enabled }}
      - setWeight: {{ .Values.strategy.canary.steps.secondStep.setWeight }}
      - pause: 
          duration: {{ .Values.strategy.canary.steps.secondStep.pause.duration }}
      {{- if .Values.strategy.canary.steps.secondStep.analysis.enabled }}
      - analysis:
          templates:
          - templateName: {{ .Values.strategy.canary.steps.secondStep.analysis.templateName }}
          args:
          - name: service-name
            value: {{ .Values.application.name | quote }}
          - name: service-port
            value: {{ .Values.service.port | quote }}
          - name: context-path
            value: {{ .Values.analysisPath | quote }}
      {{- end }}    
      {{- end }}    
      {{- if .Values.strategy.canary.steps.thirdStep.enabled }}
      - setWeight: {{ .Values.strategy.canary.steps.thirdStep.setWeight }}
      - pause: 
          duration: {{ .Values.strategy.canary.steps.thirdStep.pause.duration }}
      {{- end }}    
      {{- if .Values.strategy.canary.steps.thirdStep.analysis.enabled }}
      - analysis:
          templates:
          - templateName: {{ .Values.strategy.canary.steps.thirdStep.analysis.templateName }}
          args:
          - name: service-name
            value: {{ .Values.application.name | quote }}
          - name: service-port
            value: {{ .Values.service.port | quote }}
          - name: context-path
            value: {{ .Values.analysisPath | quote }}
      {{- end }}    
  {{- end }}