apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  labels:
    {{- include "helm-template.labels" . | nindent 4 }}
    app: {{ .Values.application.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "helm-template.selectorLabels" . | nindent 4 }}
